macro: Properly handle input parameters for built-in
For built-in types, the parameters of Macro sometimes have parsing errors,
and sometimes they can prevent the program from running.

This commit enables Macro to correctly parse built-in input parameters.

Example 1:

    macro test(pid) {
      printf("%d\n", pid);
    }
    begin { test(1); }

    Expect: 1
    Output: 16614

Example 2:

    macro test(arg0, arg1) {
      printf("%d %d\n", arg0, arg1);
    }
    begin { test(1, 2); }

    Expect: 1 2
    Output: ...
            ERROR: The arg0 builtin can only be used with 'kprobes', 'uprobes' and 'usdt' probes

Signed-off-by: Rong Tao <rongtao@cestc.cn>