Warn on low log space in verbose mode
Prompt a message when there is insufficient log space in verbose mode.
This will let the user know what may have happened and allow them to
make adjustments.

Normally, logging is not used by default (log_level=0). However, in
verbose mode, enabling logging may cause failure (ENOSPC). This can
cause the same command or script to succeed in non-verbose mode but
fail in verbbose mode, which can confuse users.

For example (source code [1]):
    $ sudo ./str_concat.bt # success
    $ sudo ./str_concat.bt -v # failed (Users will be very confused)
    ....
    ERROR: Error loading BPF program for begin_1. Error code: -28.
    Kernel error log:
    processed 87034 insns (limit 1000000) max_states_per_insn 4 total_states 2811 peak_states 136 mark_read 31

If the error is ENOSPC, prompt the user to set a larger log space:

    $ sudo ./str_concat.bt -v # failed (but give some advice)
    ....
    ERROR: Error loading BPF program for begin_1. Error code: -28 (No space left on device).
    Kernel error log:
    processed 87034 insns (limit 1000000) max_states_per_insn 4 total_states 2811 peak_states 136 mark_read 31

    Increasing the log buf size might solve this problem.  `config = {log_size = 10000000; }`, or set the environment variable `BPFTRACE_LOG_SIZE=10000000 `.

[1] https://github.com/bpftrace/bpftrace/pull/5259

Signed-off-by: Rong Tao <rongtao@cestc.cn>