Use blacklist to filter unavailable kprobes
Some functions in the kernel are explicitly designated as non-kprobe, such as
do_trap() in the kernel with such a declaration:

  NOKPROBE_SYMBOL(do_trap);

So the file /sys/kernel/debug/kprobes/blacklist contains the do_trap() function.
Now, the -l parameter of bpftrace can be found in this kprobe:

  $ sudo bpftrace -l | grep do_trap
  kprobe:do_trap

If attach kprobe:do_trap will report an error directly, which is not the result
we are seeing. We should filter out this kprobe as early as possible.

  $ sudo bpftrace -e 'kprobe:do_trap {}'
  Attaching 1 probe...
  cannot attach kprobe, Invalid argument
  ERROR: Error attaching probe: 'kprobe:do_trap'

Because do_trap() is in the available_filter_functions:

  $ sudo grep do_trap /sys/kernel/debug/tracing/available_filter_functions
  do_trap

So using a blacklist to filter out do_trap() is a good solution:

  $ sudo grep do_trap /sys/kernel/debug/kprobes/blacklist
  0xffffffff846258d0-0xffffffff846259f0	do_trap

Signed-off-by: Rong Tao <rongtao@cestc.cn>